
name: Build

on:
  push:
    branches:
      - main
      - dev
      - python
  pull_request:
    branches:
      - main
      - dev
      - python
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    permissions:
      contents: write     # to be able to check out repos and generate app tokens
      actions: write      # to be able to trigger other workflows

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
      fail-fast: false

    steps:

      # since this repo is public and the action repo is not,
      # we must check out the action repo with a valid token
      # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-using-an-action-inside-a-different-private-repository-than-the-workflow
      # set up token and permissions
      - name: Generate an app token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          owner: "JITX-Inc"
          # repositories: # unset means all when specifying "owner"
          app-id: ${{ vars.GITHUBAPP_ID }}
          private-key: ${{ secrets.GITHUBAPP_PRIVATE_KEY }}
          permission-contents: write  # for committing content to a repo
          permission-actions: read    # for reading artifacts from actions

      - name: Check out Action repository
        uses: actions/checkout@v4
        with:
          repository: jitx-inc/pybuild-action
          ref: v1
          token: ${{ steps.app-token.outputs.token }}
          path: ./.github/actions/pybuild-action

      - name: Build, Test, and Deploy
        uses: ./.github/actions/pybuild-action
        with:
           python-version: "${{ matrix.python-version }}"
           run-publish: true
           hatch-index-user: ${{ vars.HATCH_INDEX_USER }}
           hatch-index-auth: ${{ secrets.HATCH_INDEX_AUTH }}
           notify-slack: true
           slack-token: ${{ secrets.SLACK_TOKEN }}
           github-user: ${{ github.actor }}
